---
title: "Datos de Policiales de Costa Rica"
author: "Erick Ruiz"
date: '2022-07-08'
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme:
      version: 3
      bootswatch: cosmo

---



```{r paquetes, message= FALSE}
library(ggthemes) 
library(plotly) 
library(kableExtra) 
library(DT) 
library(lubridate)
library(dplyr)
library(sf)
library(ggplot2)
library(leaflet)
library(shiny)
library(lubridate)
library(stringi) 
library(readr) 
library(readxl) 
library(dplyr) 
library(sf) 
library(terra) 
library(leaflet) 
```

```{r lectura-datos-cantones}


cantones <-
  st_read(dsn = "cantones_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```

```{r lectura-datos-policiales}


Datos_policiales <-
  readxl::read_xls( "estadisticaspoliciales2021.xls", 
  col_names = TRUE,
 .name_repair = "unique")
 
```


```{r lista-cantones}
lista_cantones <- unique(cantones$canton)
lista_cantones <- sort(lista_cantones)
lista_cantones <- c("Todos", lista_cantones)
```


```{r Union, message = FALSE}

cantones <-
  cantones %>%
  mutate(lista_cantones = tolower(stri_trans_general(canton, id = "Latin-ASCII")))

Datos_policiales <-
  Datos_policiales %>%
  mutate(lista_cantones = tolower(stri_trans_general(Canton, id = "Latin-ASCII")))

Datos_policiales %>%
  left_join(
    dplyr::select(st_drop_geometry(cantones),
                  lista_cantones, cod_canton),
    by = "lista_cantones",
    copy = FALSE,
    keep = FALSE
  ) %>%
  filter(is.na(cod_canton) & lista_cantones != "desconocido") %>% 
  distinct(lista_cantones) 
Datos_policiales <-
  Datos_policiales %>%
  left_join(
    dplyr::select(
      st_drop_geometry(cantones),
      cod_canton,
      lista_cantones
    ),
    by = "lista_cantones",
    copy = FALSE,
    keep = FALSE
  )
Delito_x_canton <-
  Datos_policiales %>%
  count(cod_canton, name = "Delitos")


cantones_delitos <-
  cantones %>%
  left_join(
    Delito_x_canton,
    by = "cod_canton",
    copy = FALSE,
    keep = FALSE
  )

```

 Row {data-height=10}
-----------------------------------------------------------------------


### **Fuente de los datos: [Instituto Geográfico Nacional (IGN)](http://geos.snitcr.go.cr/be/IGN_5/wfs) y [Organismo de Investigación Judicial(OIJ)](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos)  **


Row {data-height=590}
-----------------------------------------------------------------------


```{r mapa, message = FALSE}
# Mapa
colores_cantones_delitos <-
  colorNumeric(palette = "Reds",
               domain = cantones_delitos$Delitos,
               na.color = "transparent")
leaflet() %>%
  setView(
    lng = -84.19452,
    lat = 9.572735,
    zoom = 7) %>%
  addTiles(group = "OpenStreetMap") %>% 
  addPolygons(
    
    data = cantones_delitos,
    fillColor = ~ colores_cantones_delitos(cantones_delitos$Delitos),
    fillOpacity = 0.8,
    color = "black",
    stroke = TRUE,
    weight = 1.0,
    popup = paste(
      
      paste(
        "<strong>Cantón:</strong>",
        cantones_delitos$canton
      ),
      paste(
        "<strong>Delitos:</strong>",
        cantones_delitos$Delitos
      ),
      sep = '<br/>'
    ),
    group = "Delitos en cantones"
  ) %>%
  addLayersControl(
    # control de capas
    baseGroups = c("OpenStreetMap"),
    overlayGroups = c("Delitos en cantones")
  ) %>%
  addLegend(
    
    position = "bottomleft",
    pal = colores_cantones_delitos,
    values = cantones_delitos$Delito,
    group = "Delitos",
    title = "Cantidad de delitos"
)
```



```{r Tabla, message=FALSE }
renderDT({
  Datos_policiales <-
  
Datos_policiales %>%
  dplyr::select("Delito","Fecha","Victima","Edad","Genero","Provincia","Canton") %>%
  datatable(
    options = list(
      pageLength = 5,
    
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json') 
    ),
    colnames = c(
      
      "Delitos",
      "Fecha",
      "Víctima",
      "Edad",
      "Género",
      "Provincia",
      "Cantón"
    ))
})
```

Row {data-height=400}
-----------------------------------------------------------------------

```{r Grafico_cantidad_delito_1, message=FALSE}
grafico_cantidad_delitos_1 <-
  Datos_policiales %>%
  count(Delito) %>% 
  ggplot(aes(x = reorder(Delito, n), y = n)) +
  geom_bar(stat = "identity") +
  xlab("Tipo de delito") +
  ylab("Cantidad") +
  coord_flip() +
  theme_hc() 
grafico_cantidad_delitos_1 %>%
  ggplotly() %>% 
  config(locale = 'es')
```


```{r Grafico_delito_mes}
delitos_mes <-
  Datos_policiales %>%
  mutate(fecha = lubridate::month(Fecha))
meses <-
  c(
    "Enero",
    "Febrero",
    "Marzo",
    "Abril",
    "Mayo",
    "Junio",
    "Julio",
    "Agosto",
    "septiembre",
    "Octubre",
    "Noviembre",
    "Diciembre"
  )
  delitos_mes <- delitos_mes %>%
  count(fecha) %>%
  ggplot(aes(x = reorder(fecha, n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos por mes") +
  xlab("Mes") +
  ylab("Cantidad") +
  theme()
  
ggplotly(delitos_mes) %>% config(locale = 'es')
```

```{r Grafico_cantidad_delitos_genero}
grafico_cantidad_delitos_genero <-
  Datos_policiales %>%
  ggplot(aes(x = Delito, fill = Genero)) +
  geom_bar(position = "fill") +
  xlab("Tipo de delito") +
  ylab("Cantidad") +
  labs(fill = "Género") +
  coord_flip() +
  theme_minimal()
ggplotly(grafico_cantidad_delitos_genero) %>% config(locale = 'es')
  
```
